name: Favor PR branch on conflicts
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: write
jobs:
  autoupdate:
    # Only push back to branches in the same repo (can’t push to forks)
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: |
          git config user.name "automerge-bot"
          git config user.email "automerge-bot@users.noreply.github.com"
          git fetch origin ${{ github.base_ref }}
          # On the PR branch, prefer PR changes on conflicts
          git merge -X ours origin/${{ github.base_ref }} || true
          git push
